FROM node:20.7.0-alpine3.18 as build

WORKDIR /react

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine3.18-slim

COPY --from=build /react/dist /usr/share/nginx/html

COPY --from=build /react/src/translation /usr/share/nginx/html/src/translation

COPY --from=build /react/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]