import axiosRetry from "axios-retry";
import axios from "axios";
import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { toast } from "react-toastify";
import AdminLayout from "../../components/admin/AdminLayout";
import { useAuth } from "../../components/AuthProvider";
import getApiUrl from "../../utils/url";

axiosRetry(axios, {
    retries: 3,
    retryCondition(error) {
        switch (error.response.status) {
            case 500:
                return true;
            default:
                return false;
        }
    },
    retryDelay: axiosRetry.exponentialDelay,
});

const AdminPage = () => {
    const descriptor = [
        {
            name: "Account",
            route: "admin/account",
            columns: [
                {
                    name: "email",
                    headerName: "Email",
                    type: "string",
                    id: true,
                    required: true, //Only if we need to specify the id (If it is not genereted automaticly)

                    checks: [
                        //not null check by default
                        {
                            type: "regex",
                            regex: "^[a-zA-Z0-9_.+-âàéèêùûî]+@[a-zA-Z0-9-]+\\.[\\w-]{2,4}$",
                            scope: "g",
                            error_msg: "Email is invalid",
                        },
                    ],
                },
                {
                    name: "password",
                    headerName: "Password",
                    type: "string",
                    hidden: true,
                },
                {
                    name: "name",
                    headerName: "Name",
                    type: "string",
                },
                {
                    name: "first_name",
                    headerName: "First Name",
                    type: "string",
                },
                {
                    name: "is_admin",
                    headerName: "Is Admin",
                    type: "boolean",
                },
            ],
        },
        {
            name: "Affiliation",
            route: "admin/affiliation",
            columns: [
                {
                    name: "garden_id",
                    headerName: "Garden ID",
                    type: "number",
                    id: true,
                    required: true,
                    checks: [
                        {
                            type: "greater", //arg0 > arg1
                            arg0: {
                                type: "property",
                                name: "garden_id",
                            },
                            arg1: {
                                type: "litteral",
                                value: 0,
                            },
                            error_msg: "Garden ID must be greater than 0",
                        },
                    ],
                },
                {
                    name: "user_id",
                    headerName: "User Id",
                    type: "string",
                    id: true,
                    required: true,
                    checks: [
                        //not null check by default
                        {
                            type: "regex",
                            regex: "^[a-zA-Z0-9_.+-âàéèêùûî]+@[a-zA-Z0-9-]+\\.[\\w-]{2,4}$",
                            scope: "g",
                            error_msg: "User Id is invalid",
                        },
                    ],
                },
                {
                    name: "role",
                    headerName: "Role",
                    type: "string",
                    selection: ["affiliate", "admin"],
                    readonly: true,
                },
                {
                    name: "join_date",
                    headerName: "Join Date",
                    type: "date",
                    autogenerated: true,
                },
            ],
        },
        {
            name: "Garden",
            route: "admin/garden",
            columns: [
                {
                    //Auto generated
                    name: "id",
                    headerName: "Id",
                    type: "number",
                    id: true,
                },
                {
                    name: "name",
                    headerName: "Name",
                    type: "string",
                },
                {
                    name: "address",
                    headerName: "Address",
                    type: "address",
                },
                {
                    name: "date",
                    headerName: "Date",
                    type: "date",
                },
                {
                    name: "plan",
                    headerName: "Plan",
                    type: "json",
                },
            ],
        },
        {
            name: "Area",
            route: "admin/area",
            columns: [
                {
                    //Auto generated
                    name: "id",
                    headerName: "Id",
                    type: "number",
                    id: true,
                },
                {
                    name: "garden_id",
                    headerName: "Garden Id",
                    type: "number",
                    checks: [
                        {
                            type: "greater", //arg0 > arg1
                            arg0: {
                                type: "property",
                                name: "garden_id",
                            },
                            arg1: {
                                type: "litteral",
                                value: 0,
                            },
                            error_msg: "Garden Id must be greater than 0",
                        },
                    ],
                    readonly: true,
                    required: true,
                },
                {
                    name: "area_index",
                    headerName: "Index",
                    type: "number",
                    checks: [
                        {
                            type: "greaterEq", //arg0 > arg1
                            arg0: {
                                type: "property",
                                name: "area_index",
                            },
                            arg1: {
                                type: "litteral",
                                value: 0,
                            },
                            error_msg: "Index must be greater or equal of 0",
                        },
                    ],
                },
                {
                    name: "name",
                    headerName: "Name",
                    type: "string",
                },
                {
                    name: "description",
                    headerName: "Description",
                    type: "string",
                    optional: true,
                },
            ],
        },
        {
            name: "Task",
            route: "admin/task",
            columns: [
                {
                    //Auto generated
                    name: "id",
                    headerName: "Id",
                    type: "number",
                    id: true,
                },
                {
                    name: "area_id",
                    headerName: "Area Id",
                    type: "number",
                    checks: [
                        {
                            type: "greater", //arg0 > arg1
                            arg0: {
                                type: "property",
                                name: "area_id",
                            },
                            arg1: {
                                type: "litteral",
                                value: 0,
                            },
                            error_msg: "Area Id must be greater than 0",
                        },
                    ],
                },
                {
                    name: "title",
                    headerName: "Title",
                    type: "string",
                },
                {
                    name: "start_date",
                    headerName: "Start Date",
                    type: "datetime",
                    checks: [
                        {
                            type: "greater", //arg0 > arg1
                            arg0: {
                                type: "property",
                                name: "deadline_date",
                            },
                            arg1: {
                                type: "property",
                                name: "start_date",
                            },
                            error_msg: "Deadline must be after Start date",
                        },
                    ],
                },
                {
                    name: "deadline_date",
                    headerName: "Deadline",
                    type: "datetime",
                },
                {
                    name: "validated",
                    headerName: "Validated",
                    type: "boolean",
                    autogenerated: true,
                },
                {
                    name: "description",
                    headerName: "Description",
                    type: "string",
                },
            ],
        },
    ];

    const navigate = useNavigate();
    const { t } = useTranslation();
    const { setToken } = useAuth();

    const [loading, setLoading] = useState(true);

    useEffect(() => {
        onLoad();
    }, []);

    const onLoad = async () => {
        axios
            .get(getApiUrl("/v1/user/is-admin"))
            .then((response) => {
                setLoading(false);
            })
            .catch((reason) => {
                if (reason.code === "ERR_NETWORK") {
                    navigate("/");
                    toast(t("components.notification.timed-out"), {
                        type: "error",
                    });
                } else if (
                    reason.response.status == 401 ||
                    reason.response.status == 404
                ) {
                    //Token invalid or header not found
                    toast(t("components.notification.must_be_logged_in"), {
                        type: "warning",
                    });
                    setTimeout(() => {
                        navigate("/login");
                    }, 1000);
                } else if (
                    reason.response.status === 401 &&
                    reason.response.data == "TOKEN_INVALID"
                ) {
                    setToken();
                    setTimeout(() => {
                        navigate("/login");
                    }, 1000);
                    toast(t("components.notification.must_be_logged_in"), {
                        type: "error",
                    });
                } else if (reason.response.status == 403) {
                    toast(t("components.notification.forbidden"), {
                        type: "error",
                    });
                    setTimeout(() => {
                        navigate("/");
                    }, 1000);
                } else {
                    toast(t("components.notification.fetch"), {
                        type: "error",
                    });
                    setTimeout(() => {
                        navigate("/");
                    }, 1000);
                }
            });
    };

    if (loading) {
        return (
            <div className="flex justify-center items-center w-screen h-screen bg-bg_gray overflow-hidden outline-none">
                <svg
                    aria-hidden="true"
                    className="w-12 h-12 mr-2 animate-spin fill-green1 text-gray0"
                    viewBox="0 0 100 101"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z"
                        fill="currentColor"
                    />
                    <path
                        d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z"
                        fill="currentFill"
                    />
                </svg>
                <span className="sr-only">Loading...</span>
            </div>
        );
    } else {
        return <AdminLayout descriptor={descriptor} />;
    }
};

export default AdminPage;
